version: '3'

services:
  backend:
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./dockerfile
    image: "amitpotdukhe/backend-a"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./dockerfile
    image: "amitpotdukhe/frontend-a"
    ports:
      - "3000:3000"
    links:
      - "backend:be"